[pytest]
addopts =
    -s
    -v
    --strict-markers
    --html=reports/report.html
    --self-contained-html

testpaths = tests

markers =
    e2e: Alur E2E lengkap Modul 1-8 (continuous, 1 browser session)
    dashboard: Modul 1 - Dashboard
    tugas: Modul 2 - Tugas
    masuk: Modul 3 - Masuk
    disposisi_keluar: Modul 4 - Disposisi Keluar
    progress_surat: Modul 5 - Progress Surat
    surat_dinas_eksternal: Modul 6 - Surat Keluar Eksternal
    nota_dinas_keluar: Modul 7 - Nota Dinas Keluar
    logout: Modul 8 - Logout

log_date_format = %Y-%m-%d %H:%M:%S
